version: '3'
services:
  backend:
    container_name: backend_server
    image: api:v2
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./apikeys.conf:/etc/nginx/apikeys.conf
    ports:
      - 80:80
